<?php
/**
 * Created by PhpStorm.
 * User: 119
 * Date: 01.03.2018
 * Time: 18:20
 */

namespace Test\Config;


use Iguan\Common\Remote\SocketClient;

class MySocketClient extends SocketClient
{

    /**
     * @var null
     */
    private $remoteSocket;

    private $persist;

    public function __construct($remoteSocket = null)
    {
        parent::__construct($remoteSocket);
        $this->remoteSocket = $remoteSocket;
    }

    public function persist()
    {
        parent::persist(); // TODO: Change the autogenerated stub
        $this->persist = true;
    }

    public function isPersist() {
        return $this->persist;
    }

    public function write($data)
    {

    }

    /**
     * @return null
     */
    public function getRemoteSocket()
    {
        return $this->remoteSocket;
    }
}